name: Dillon Hafer
author: Dillon Hafer
baseurl: /
description: A place for blog posts, interesting links, things I learn, and more.
github: http://www.github.com/dillonhafer
twitter: http://www.twitter.com/dillonhafer
linkedin: http://www.linkedin.com/in/dillonhafer
email: dh[at]dillonhafer.com


permalink: /:year/:month/:day/:title
highlighter: rouge

defaults:
  - scope:
      path: ""
      permalink: /:title
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
